### ISSUE TITLE
Document what the NREMT requirements for recertification

### ISSUE THREAD

**Issue by andrewpcodes** [aptracky/ems-cert-track#12]
Due Date:
6/7/22

Description:
- Describe the current requirements by the NREMT for recertification by continuing education

Requirements:
- Document the current NREMT continuing education requirements

**Comment by spathanasf1** [comment]
https://drive.google.com/file/d/1R9RUOqwKLMooC-x9Czgf-bqSPLQ-ne26/view?usp=sharing
