### ISSUE TITLE
Design Account Creation Screen

### ISSUE THREAD

**Issue by labried2atwit** [aptracky/ems-cert-track#4]
Requirements
- Create initial design for the account creation page.

**Comment by andrewpcodes** [comment]
<img width="670" alt="createAccount" src="https://user-images.githubusercontent.com/20158007/172423773-a19e7a69-fce2-42db-98b6-34f8a29b555d.png">
<img width="670" alt="SignIn Image" src="https://user-images.githubusercontent.com/20158007/172423800-4bd88eb9-d054-4113-a415-18b7adc0b570.png">
