### ISSUE TITLE
Design Login/Logout Menu

### ISSUE THREAD

**Issue by labried2atwit** [aptracky/ems-cert-track#7]
Requirements
- Create initial design for menu that facilitates logging in and out.

**Comment by andrewpcodes** [comment]
<img width="670" alt="SignIn Image" src="https://user-images.githubusercontent.com/20158007/172423062-9229e687-b36d-413f-91e8-701d06695e1d.png">
<img width="670" alt="createAccount" src="https://user-images.githubusercontent.com/20158007/172423083-7b82b1e1-1f73-4a9e-ad2f-91762125dbef.png">
